title: Wiki Catalog
author: "solipsse"

sphinx:
  extra_extension:
    - sphinx_inline_tabs
    - sphinx_proof
  # config:
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # html_theme: furo
parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - html_admonition
    - deflist
    - colon_fence
    - html_image
    - linkify
    - fieldlist
    - replacements
    - substitution
    - strikethrough
    - attrs_inline
    - tasklist  # Additional extension
html:
  analytics:
    google_analytics_id: G-LYW22V2HG4
