title: Wiki Catalog
author: "solipsse"

sphinx:
  extra_extension:
    - sphinx_inline_tabs
    - sphinx_proof
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax3_config:
      tex:
        macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat": ["\\left[\\begin{array}", 0]
          "emat": ["\\end{array}\\right]", 0]
    # html_theme: furo
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    - colon_fence
    - deflist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist  # Additional extension
html:
  analytics:
    google_analytics_id: G-LYW22V2HG4