name: Update NBViewer Links Workflow

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger this workflow on

jobs:
  update_links:
    runs-on: ubuntu-latest  # You can choose the appropriate runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update NBViewer Links
      uses: KensingtonOscupant/nbviewer-flush-cache-action@v1.0.4
      with:
        file_path: 'file_path' # IMPORTANT! path to the file where you would like to have the links changed, for the readme it would be 'README.md'
        commit_email: 'your_email@example.com'  # Optional, no need to set this one
        commit_username: 'YourUsername'         # Optional, no need to set this one
