name: Update NBViewer Links Workflow

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger this workflow on

jobs:
  update_links:
    runs-on: ubuntu-latest  # You can choose the appropriate runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update NBViewer Links
      uses: KensingtonOscupant/nbviewer-flush-cache-action@v1.0.3
      with:
        commit_email: 'totallystudyign@gmail.com' 
        commit_username: 'solipsse'
